### ISSUE TITLE
function:example09 branch-ignacio

### ISSUE THREAD

**Issue by Redhotnacho** [molavec/js-examples#12]
function\example09.js:31
((text) => {
^

TypeError: (intermediate value)(...) is not a function

**Comment by molavec** [comment]
Resuelto: faltaba punto y coma (;) para el uso apropiado de la invocación de una función anónima.

**Comment by molavec** [comment]
Resuelto: faltaba punto y coma (;) para el uso apropiado de la invocación de una función anónima.
